-- ============================================================
-- Hamid Ali Awan Portfolio
-- Supabase PostgreSQL Database Schema
-- ============================================================
--
-- This database supports:
--   1. Contact messages
--   2. Unlimited portfolio projects
--   3. Protected Flask admin CMS
--
-- The Flask server communicates with Supabase using the
-- server-side SUPABASE_KEY.
--
-- IMPORTANT:
-- Keep the SUPABASE_KEY / service-role key private.
-- Never put it inside HTML, JavaScript, GitHub, or frontend code.
-- ============================================================


-- ============================================================
-- 1. MESSAGES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,

    email TEXT NOT NULL,

    subject TEXT NOT NULL DEFAULT '',

    message TEXT NOT NULL,

    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    is_read BOOLEAN NOT NULL DEFAULT FALSE
);


-- ============================================================
-- 2. PROJECTS TABLE
-- ============================================================
--
-- This table is NOT limited to four projects.
--
-- You can add:
--   4 projects
--   10 projects
--   50 projects
--   100+ projects
--
-- Your Flask admin panel can add/edit/delete projects
-- dynamically.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title TEXT NOT NULL,

    description TEXT NOT NULL,

    tags TEXT NOT NULL DEFAULT '',

    image_url TEXT NOT NULL DEFAULT '',

    github_url TEXT NOT NULL DEFAULT '',

    live_url TEXT NOT NULL DEFAULT '',

    sort_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 3. ENABLE ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 4. SERVER-SIDE ACCESS
-- ============================================================
--
-- Your Flask application uses SUPABASE_KEY on the server.
--
-- If SUPABASE_KEY is the service-role key, Supabase's
-- server-side request bypasses normal RLS restrictions.
--
-- Therefore, we intentionally do NOT create public INSERT,
-- UPDATE, DELETE or SELECT policies here.
--
-- This prevents anonymous users from directly accessing
-- your database through the public API.
-- ============================================================


-- ============================================================
-- 5. OPTIONAL INDEXES
-- ============================================================
--
-- These indexes improve sorting and message retrieval.
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_projects_sort_order
ON public.projects (sort_order);

CREATE INDEX IF NOT EXISTS idx_projects_created_at
ON public.projects (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_received_at
ON public.messages (received_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_is_read
ON public.messages (is_read);


-- ============================================================
-- 6. SAMPLE PROJECTS
-- ============================================================
--
-- These are optional starter projects.
--
-- DELETE this section if you don't want sample projects.
--
-- You can add unlimited projects later from your Flask
-- admin dashboard.
-- ============================================================

INSERT INTO public.projects
(
    title,
    description,
    tags,
    image_url,
    github_url,
    live_url,
    sort_order
)
SELECT
    'AI Power Consumption Prediction',
    'Machine learning system for power consumption prediction and energy recommendations.',
    'Python,Machine Learning,Flask',
    '',
    '',
    '',
    1
WHERE NOT EXISTS (
    SELECT 1
    FROM public.projects
    WHERE title = 'AI Power Consumption Prediction'
);


INSERT INTO public.projects
(
    title,
    description,
    tags,
    image_url,
    github_url,
    live_url,
    sort_order
)
SELECT
    'SafarPakistan',
    'Travel web application for exploring and managing Pakistan travel packages.',
    'Flask,Python,HTML,CSS,JavaScript',
    '',
    '',
    '',
    2
WHERE NOT EXISTS (
    SELECT 1
    FROM public.projects
    WHERE title = 'SafarPakistan'
);


INSERT INTO public.projects
(
    title,
    description,
    tags,
    image_url,
    github_url,
    live_url,
    sort_order
)
SELECT
    'Student Result Prediction',
    'Machine learning project using student performance features for prediction.',
    'Python,scikit-learn,pandas',
    '',
    '',
    '',
    3
WHERE NOT EXISTS (
    SELECT 1
    FROM public.projects
    WHERE title = 'Student Result Prediction'
);


INSERT INTO public.projects
(
    title,
    description,
    tags,
    image_url,
    github_url,
    live_url,
    sort_order
)
SELECT
    'Data Analysis Dashboard',
    'Interactive dashboard concept for exploring data and visualizing useful insights.',
    'Python,Flask,JavaScript,Charts',
    '',
    '',
    '',
    4
WHERE NOT EXISTS (
    SELECT 1
    FROM public.projects
    WHERE title = 'Data Analysis Dashboard'
);


-- ============================================================
-- END OF SCHEMA
-- ============================================================