-- Supabase setup for Hamid Ali Awan Portfolio
-- Run this once in Supabase SQL Editor.
-- Then add SUPABASE_URL and SUPABASE_KEY (service role key) to Vercel.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null default '',
  message text not null,
  received_at timestamptz not null default now(),
  is_read boolean not null default false
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tags text not null default '',
  image_url text not null default '',
  github_url text not null default '',
  live_url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;
alter table public.projects enable row level security;

-- No public policies are created. The Flask server talks to Supabase
-- using the server-side service-role key, which bypasses RLS.
